# Generated by Django 4.1.4 on 2023-01-06 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_amounttake_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounttake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Пользователь'),
        ),
    ]
