# Generated by Django 4.1.4 on 2023-01-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_amounttake_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amounttake',
            name='category',
        ),
        migrations.AddField(
            model_name='amounttake',
            name='name_of_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', to_field='category_name', verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Категория'),
        ),
    ]
