# Generated by Django 4.1.4 on 2023-01-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_amounttake_name_of_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounttake',
            name='name_of_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, verbose_name='Категория'),
        ),
    ]
