# Generated by Django 4.1.4 on 2023-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_amounttake_name_of_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounttake',
            name='name_of_category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя категории'),
        ),
    ]
