# Generated by Django 4.1.4 on 2023-01-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finuser',
            name='send_messages',
        ),
    ]
